import { HighlightStyle, syntaxHighlighting } from '@codemirror/language'
import { EditorView } from '@codemirror/view'
import { tags } from '@lezer/highlight'

// Colors come from CSS custom properties so the editor follows the app theme without reconfiguring.
const zenTheme = EditorView.theme({
  '&': {
    color: 'var(--ink)',
    backgroundColor: 'transparent',
    fontSize: 'var(--editor-size)',
  },
  '&.cm-focused': { outline: 'none' },
  '.cm-scroller': {
    fontFamily: 'var(--editor-font)',
    lineHeight: 'var(--editor-leading)',
  },
  '.cm-content': {
    padding: '0 0 45vh',
    caretColor: 'var(--caret)',
  },
  '.cm-line': { padding: '0' },
  '.cm-cursor, .cm-dropCursor': { borderLeftColor: 'var(--caret)', borderLeftWidth: '2px' },
  '&.cm-focused > .cm-scroller > .cm-selectionLayer .cm-selectionBackground, .cm-selectionBackground, .cm-content ::selection':
    { backgroundColor: 'var(--selection)' },
  '.cm-placeholder': { color: 'var(--faint)', fontStyle: 'italic' },
  '.cm-snippet': {
    color: 'var(--accent-ink)',
    backgroundColor: 'var(--accent-wash)',
    borderRadius: '5px',
    padding: '0.08em 0.28em',
    margin: '0 -0.04em',
    fontFamily: 'var(--ui-font)',
    fontSize: '0.84em',
    fontWeight: '550',
    letterSpacing: '0.01em',
    whiteSpace: 'nowrap',
  },
  '.cm-snippet-empty': {
    backgroundColor: 'transparent',
    boxShadow: 'inset 0 0 0 1px var(--accent-wash-strong)',
  },
  '.cm-snippet-missing': {
    color: 'var(--muted)',
    backgroundColor: 'transparent',
    boxShadow: 'inset 0 0 0 1px var(--line-strong)',
  },
  '.cm-variable': {
    color: 'var(--variable-ink)',
    backgroundColor: 'var(--variable-wash)',
    borderRadius: '5px',
    padding: '0.08em 0.28em',
    margin: '0 -0.04em',
    fontFamily: 'var(--mono-font)',
    fontSize: '0.8em',
    fontWeight: '550',
    whiteSpace: 'nowrap',
  },
  '.cm-variable-def': { backgroundColor: 'transparent', boxShadow: 'inset 0 0 0 1px var(--variable-wash-strong)' },
  // Definitions aren't copied, so they read as settings rather than prose.
  '.cm-line.cm-variable-line': {
    color: 'var(--ink-soft)',
    fontFamily: 'var(--mono-font)',
    fontSize: '0.8em',
    paddingLeft: '10px',
    boxShadow: 'inset 2px 0 0 var(--variable-wash-strong)',
  },
  '.cm-line.cm-variable-line .cm-variable': { fontSize: '1em' },
  // A block's value is part of what gets copied, so it keeps the prose font, with a rule tying it to its name.
  '.cm-line.cm-variable-block-line': { paddingLeft: '10px', boxShadow: 'inset 2px 0 0 var(--variable-wash)' },
  '.cm-variable-fold, .cm-variable-fold-button': {
    font: 'inherit',
    fontSize: '0.95em',
    color: 'var(--variable-ink)',
    backgroundColor: 'var(--variable-wash)',
    border: 'none',
    borderRadius: '5px',
    padding: '0.05em 0.5em',
    margin: '0 0.35em',
    cursor: 'pointer',
    verticalAlign: 'baseline',
  },
  '.cm-variable-fold:hover, .cm-variable-fold-button:hover': { backgroundColor: 'var(--variable-wash-strong)' },
  '.cm-variable-fold-button': { backgroundColor: 'transparent', color: 'var(--muted)', margin: '0 0.6em' },
  // An inline definition shows its value in place, underlined so it reads as the value being set.
  '.cm-variable-brace': { color: 'var(--faint)', fontFamily: 'var(--mono-font)', fontSize: '0.8em' },
  '.cm-variable-value': { textDecoration: 'underline 1.5px var(--variable-wash-strong)', textUnderlineOffset: '0.2em' },
  '.cm-snippet-tooltip-name.cm-variable-tooltip-name': { color: 'var(--variable-ink)', fontFamily: 'var(--mono-font)' },
  // Tasks hang the box in front of the text, so wrapped lines and nested tasks line up under their text.
  '.cm-line.cm-task-line': {
    '--task-step': '1.6em',
    paddingLeft: 'calc((var(--task-depth) + 1) * var(--task-step))',
    textIndent: 'calc(-1 * var(--task-step))',
  },
  '.cm-task-marker': {
    display: 'inline-flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: '0.35em',
    minWidth: 'var(--task-step)',
    paddingRight: '0.55em',
    boxSizing: 'border-box',
    textIndent: '0',
    verticalAlign: 'top',
    height: 'calc(1em * var(--editor-leading))',
  },
  '.cm-task-number': {
    fontFamily: 'var(--ui-font)',
    fontSize: '0.78em',
    fontWeight: '550',
    color: 'var(--faint)',
    fontVariantNumeric: 'tabular-nums',
  },
  '.cm-task-box': {
    position: 'relative',
    flexShrink: '0',
    width: '1.05em',
    height: '1.05em',
    boxSizing: 'border-box',
    border: '1.5px solid var(--faint)',
    borderRadius: '50%',
    transition: 'border-color 0.15s, background-color 0.2s, box-shadow 0.2s',
  },
  // A wider invisible target, so the small circle is easy to hit on touch screens.
  '.cm-task-box::before': { content: '""', position: 'absolute', inset: '-0.4em' },
  '.cm-content[contenteditable=true] .cm-task-box': { cursor: 'pointer' },
  '.cm-content[contenteditable=true] .cm-task-box:hover': {
    borderColor: 'var(--accent)',
    boxShadow: '0 0 0 3px var(--accent-wash)',
  },
  '.cm-task-box.is-checked': { borderColor: 'var(--accent)', backgroundColor: 'var(--accent)' },
  // The check is cut from the page color, so it reads on every accent in both themes.
  '.cm-task-box.is-checked::after': {
    content: '""',
    position: 'absolute',
    inset: '0',
    backgroundColor: 'var(--bg)',
    maskImage:
      "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M4.6 8.4l2.3 2.3 4.5-4.8' fill='none' stroke='black' stroke-width='1.9' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E\")",
    maskSize: '100% 100%',
  },
  // Done items step back rather than being crossed out, so the list stays easy to read.
  '.cm-line.cm-task-line.is-done': { color: 'var(--muted)' },
  '.cm-line.cm-task-line.is-done .cm-task-number': { opacity: '0.7' },
  '.cm-tooltip': {
    border: '1px solid var(--line)',
    backgroundColor: 'var(--surface-raised)',
    color: 'var(--ink)',
    borderRadius: '12px',
    boxShadow: 'var(--shadow-pop)',
    overflow: 'hidden',
    fontFamily: 'var(--ui-font)',
  },
  '.cm-tooltip.cm-tooltip-autocomplete': { padding: '6px' },
  '.cm-tooltip.cm-tooltip-autocomplete > ul': {
    fontFamily: 'var(--ui-font)',
    fontSize: '14px',
    maxHeight: '18em',
    minWidth: '260px',
    maxWidth: 'min(460px, 90vw)',
  },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > li': {
    padding: '7px 10px',
    borderRadius: '8px',
    lineHeight: '1.35',
    display: 'flex',
    alignItems: 'baseline',
    gap: '10px',
  },
  '.cm-tooltip-autocomplete ul li[aria-selected]': {
    backgroundColor: 'var(--accent-wash)',
    color: 'var(--ink)',
  },
  '.cm-completion-variable .cm-completionLabel': { color: 'var(--variable-ink)', fontFamily: 'var(--mono-font)' },
  '.cm-completionLabel': { fontWeight: '550', color: 'var(--accent-ink)', flexShrink: '0' },
  '.cm-completionMatchedText': { textDecoration: 'none', color: 'var(--ink)' },
  '.cm-completionDetail': {
    color: 'var(--muted)',
    fontStyle: 'normal',
    marginLeft: 'auto',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '13px',
  },
  '.cm-completionInfo': { display: 'none' },
  '.cm-completionPaste': { display: 'none', flexShrink: '0' },
  '.cm-tooltip-autocomplete ul li[aria-selected] .cm-completionPaste': { display: 'inline' },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > completion-section': { display: 'none' },
  '.cm-snippet-tooltip': { padding: '12px 14px', maxWidth: 'min(420px, 86vw)', cursor: 'pointer' },
  '.cm-snippet-tooltip-name': { fontWeight: '600', color: 'var(--accent-ink)', fontSize: '13px', marginBottom: '6px' },
  '.cm-snippet-tooltip-body': {
    fontSize: '14px',
    lineHeight: '1.5',
    whiteSpace: 'pre-wrap',
    color: 'var(--ink-soft)',
    maxHeight: '14em',
    overflow: 'hidden',
  },
  '.cm-snippet-tooltip-hint': { marginTop: '10px', fontSize: '12px', color: 'var(--faint)' },
  '.cm-tooltip.cm-extract-tooltip': { borderRadius: '9px', padding: '3px' },
  '&:not(.cm-focused) .cm-extract-tooltip': { display: 'none' },
  '.cm-extract-tooltip button': {
    padding: '4px 10px',
    borderRadius: '7px',
    fontSize: '13px',
    fontWeight: '550',
    color: 'var(--accent-ink)',
  },
  '.cm-extract-tooltip button:hover': { backgroundColor: 'var(--accent-wash)' },
  '.cm-panels': { backgroundColor: 'var(--surface-raised)', color: 'var(--ink)', fontFamily: 'var(--ui-font)' },
  '.cm-panels.cm-panels-top': { borderBottom: '1px solid var(--line)' },
  '.cm-search': { padding: '10px 12px', fontSize: '13px' },
  '.cm-search input, .cm-search button': { fontFamily: 'var(--ui-font)', fontSize: '13px' },
  '.cm-textfield': {
    border: '1px solid var(--line-strong)',
    borderRadius: '7px',
    backgroundColor: 'var(--surface)',
    color: 'var(--ink)',
    padding: '4px 8px',
  },
  '.cm-button': {
    backgroundImage: 'none',
    backgroundColor: 'var(--surface)',
    border: '1px solid var(--line-strong)',
    borderRadius: '7px',
    color: 'var(--ink)',
    padding: '4px 10px',
  },
  '.cm-searchMatch': { backgroundColor: 'var(--highlight)', borderRadius: '3px' },
  '.cm-searchMatch-selected': { backgroundColor: 'var(--highlight-strong)' },
  '.cm-panel.cm-search [name=close]': { color: 'var(--muted)', fontSize: '18px', right: '8px', top: '6px' },
})

const zenHighlight = HighlightStyle.define([
  { tag: tags.heading1, fontWeight: '650', fontSize: '1.3em', letterSpacing: '-0.01em' },
  { tag: tags.heading2, fontWeight: '650', fontSize: '1.15em' },
  { tag: [tags.heading3, tags.heading4, tags.heading5, tags.heading6], fontWeight: '650' },
  { tag: tags.strong, fontWeight: '650' },
  { tag: tags.emphasis, fontStyle: 'italic' },
  { tag: tags.strikethrough, textDecoration: 'line-through', color: 'var(--muted)' },
  { tag: tags.monospace, fontFamily: 'var(--mono-font)', fontSize: '0.86em', color: 'var(--code-ink)' },
  { tag: tags.quote, color: 'var(--ink-soft)', fontStyle: 'italic' },
  { tag: [tags.link, tags.url], color: 'var(--accent-ink)', textDecoration: 'underline' },
  { tag: [tags.processingInstruction, tags.meta, tags.contentSeparator], color: 'var(--faint)' },
])

export const zenAppearance = [zenTheme, syntaxHighlighting(zenHighlight)]
